/**
 * Tool Executor Layer
 * Validates, authorizes, and safely executes registered Gemini tool calls.
 * Enforces strict argument sanitization, execution boundaries, and telemetry logging.
 */

const { getToolHandler, isToolRegistered } = require("./toolRegistry");

const MAX_TOOL_CALLS_PER_TURN = 3;

/**
 * Execute an approved tool call with safety guarantees
 * @param {string} toolName - Name of the requested tool
 * @param {object} args - Arguments generated by Gemini
 * @param {object} context - Execution context (e.g. sessionId)
 * @returns {Promise<object>} Tool execution result
 */
async function executeTool(toolName, args = {}, context = {}) {
  const startTime = Date.now();

  // 1. Strict Whitelist Verification
  if (!isToolRegistered(toolName)) {
    console.warn(`🛡️ [ToolExecutor] Blocked attempt to call unregistered tool: '${toolName}'`);
    return {
      success: false,
      error: "TOOL_NOT_AVAILABLE",
      message: `The tool '${toolName}' is not available or permitted.`,
    };
  }

  const handler = getToolHandler(toolName);
  if (!handler) {
    return {
      success: false,
      error: "HANDLER_NOT_FOUND",
    };
  }

  // 2. Sanitize and inject safe context
  const safeArgs = typeof args === "object" && args !== null ? { ...args } : {};
  if (context.sessionId && !safeArgs.sessionId) {
    safeArgs.sessionId = context.sessionId;
  }

  // 3. Safe Execution
  try {
    const result = await handler(safeArgs, context);
    const duration = Date.now() - startTime;

    if (process.env.NODE_ENV !== "production") {
      console.log(`🔧 [Tool] Executed '${toolName}' in ${duration}ms | Success: ${result?.success !== false}`);
    }

    return result;
  } catch (error) {
    const duration = Date.now() - startTime;
    console.error(`❌ [ToolExecutor Error on '${toolName}'] (${duration}ms):`, error?.message || error);
    return {
      success: false,
      error: "TOOL_EXECUTION_FAILED",
      message: "An internal error occurred while executing the tool.",
    };
  }
}

module.exports = {
  executeTool,
  MAX_TOOL_CALLS_PER_TURN,
};
